image: tiangolo/docker-with-compose

stages:
  - build
  - test
  - deploy

before_script:
  - chmod +x ./deploy.sh
  - chmod +x ./server/run.sh

deploy-to-staging:
  stage: deploy
  script:
    - ./deploy.sh staging
  when: manual
  only:
    - develop

deploy-to-production:
  stage: deploy
  script:
    - ./deploy.sh production
  when: manual
  only:
    - develop