image: docker:latest

stages:
  - build
  - test
  - deploy

deploy_test:
  stage: deploy
  script:
    - apk add py-pip
    - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - apk add gnupg
    - gpg --output .env --passphrase ENV_DECRYPT_PASSWORD --decrypt .env.gpg
    - docker-compose -f docker-compose.yml up -d --build
  only:
    - test