image: tiangolo/docker-with-compose

stages:
  - build
  - test
  - deploy

deploy-to-server:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.staging.yml down
    - apk --no-cache add git
    - apk --no-cache add jq
    - apk --no-cache add curl
    - chmod +x ./reset_data.sh
    - ./reset_data.sh staging
    - docker-compose -f docker-compose.yml -f docker-compose.staging.yml up -d --build
    - docker system prune -f
  when: manual
  only:
    - staging