stages:
  - build
  - test
  - deploy

deploy_test:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
    - docker system prune -f
  only:
    - test