image: docker:stable

before_script:
  - docker info

stages:
  - build
  - test
  - deploy

deploy_test:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml -f down
    - docker-compose -f docker-compose.yml -f up -d --build
    - docker system prune -f
  only:
    - test