version: '3'

services:
  server:
    build: ./server
    depends_on:
      - api-v1
    environment:
      - CONFIGS_URL
      - CONFIGS_PASSWORD
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

  api-v1:
    build: ./api-v1
    environment:
      - CONFIGS_URL
      - CONFIGS_PASSWORD
    networks:
      - backend
      - frontend

  database:
    build: ./database
    environment:
      - CONFIGS_URL
      - CONFIGS_PASSWORD
      - POSTGRES_PASSWORD=password # This gets changed in an init script but a value is needed here so Postgres authenticates users
    volumes:
      - geki-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
      - backup

volumes:
  geki-data:

networks:
  backend:
  frontend:
  backup: