version: '3'

services:
  server:
    restart: unless-stopped
    environment:
      - APP_ENV=production

  api-v1:
    restart: unless-stopped
    environment:
      - APP_ENV=production

  database:
    restart: unless-stopped
    environment:
      - APP_ENV=production

  backup:
    restart: unless-stopped
    environment:
      - APP_ENV=production