version: '3'

services:
  server:
    build: ./server
    image: geki_server:latest
    depends_on:
      - api-v1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

  api-v1:
    build: ./api-v1
    image: geki_api-v1:latest
    networks:
      - backend
      - frontend

  database:
    build: ./database
    image: geki_database:latest
    environment:
      - POSTGRES_PASSWORD=password # This gets changed in an init script but a value is needed here so Postgres authenticates users
    volumes:
      - geki-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  geki-data:

networks:
  backend:
  frontend: