version: '3'

services:
  database:
    volumes:
      - ./database/dev/scripts:/docker-entrypoint-initdb.d

  api-v1:
    environment:
      - NODE_ENV=development
    volumes:
      - ./api-v1:/app
    command: npm run start-dev

  server:
    volumes:
      - ./server/dev/api.conf:/etc/nginx/conf.d/api.conf
      - ./server/dev/ssl:/etc/ssl