version: '3'

services:
  config:
    build: ./config
    environment:
      - GOOGLE_CLIENT_EMAIL
      - GOOGLE_PRIVATE_KEY
    networks:
      - config-database
      - config-api-v1
      - config-server

  database:
    build: ./database
    depends_on:
      - config
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_USER_API_NAME
      - DB_USER_API_PASSWORD
    volumes:
      - geki-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
      - config-database
  
  api-v1:
    build: ./api-v1
    depends_on:
      - config
    networks:
      - backend
      - frontend
      - config-api-v1

  server:
    build: ./server
    depends_on:
      - config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - config-server

volumes:
  geki-data:

networks:
  backend:
  frontend:
  config-database:
  config-api-v1:
  config-server: