version: '3'

services:
  database:
    build: ./database
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_USER_API_NAME
      - DB_USER_API_PASSWORD
    volumes:
      - geki-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
  
  api:
    build: ./api
    environment:
      - PGHOST
      - PGPORT
      - PGDATABASE=${POSTGRES_DB}
      - PGUSER=${DB_USER_API_NAME}
      - PGPASSWORD=${DB_USER_API_PASSWORD}
      - DB_DATA_SCHEMA
      - DB_VIEW_SCHEMA
      - API_LOG_URL
      - API_ERROR_URL
      - API_AUTH_HOST
    networks:
      - backend
      - frontend

  server:
    build: ./server
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

volumes:
  geki-data:

networks:
  backend:
  frontend: