version: '3'

services:
  server:
    environment:
      - APP_ENV=development
    volumes:
      - ./server/dev/api.conf:/etc/nginx/conf.d/api.conf
      - ./server/dev/ssl:/etc/ssl

  database:
    environment:
      - APP_ENV=development
    volumes:
      - ./database/dev/scripts:/docker-entrypoint-initdb.d

  api-v1:
    environment:
      - APP_ENV=development
    volumes:
      - ./api-v1:/app
    command: ./wait-for.sh config:3000 -t 10 -- npm run start-dev

  config:
    environment:
      - APP_ENV=development
    volumes:
      - ./config/:/app
    command: npm run start-dev