version: '3'

services:
  backup:
    build: ./backup
    image: geki_backup:latest
    environment:
      - APP_ENV=production
    networks:
      - backend
  
  server:
    environment:
      - APP_ENV=production

  database:
    environment:
      - APP_ENV=production

  api-v1:
    environment:
      - APP_ENV=production