version: '3'

services:
  database:
    build: ./database
    env_file:
      - ./config/database/database.env
    environment:
      - NEW_USER_NAME=${DB_API_USERNAME}
      - NEW_USER_PASSWORD=${DB_API_PASSWORD}
    volumes:
      - geki-data:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - backend
  
  api:
    build: ./api
    env_file:
      - ./config/api/api.env
    environment:
      - PGUSER=${DB_API_USERNAME}
      - PGPASSWORD=${DB_API_PASSWORD}
    volumes:
      - ./api:/app
    command: npm run start-dev
    networks:
      - backend
      - frontend

  server:
    build: ./server
    volumes:
      - ./server/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

volumes:
  geki-data:

networks:
  backend:
  frontend: