version: '3'

services:
  backup:
    build:
      context: ./backup
      args:
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - BACKUP_REPO=${DB_BACKUP_URL}
    depends_on:
      - config
    environment:
      - PGHOST
      - PGPORT
      - PGDATABASE=${POSTGRES_DB}
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
  
  api-v1:
    environment:
      - APP_ENV=production