#!/bin/sh
## Make sure the file has LF line endings!
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE $DB_USER_API_NAME NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN PASSWORD '$DB_USER_API_PASSWORD';
    GRANT CONNECT ON DATABASE geki TO api;
EOSQL