INSERT INTO geki_data.series (title,alternative_title) VALUES 
('Wotakoi: Love is Hard for Otaku','Wotaku ni Koi wa Muzukashii')
,('Re:Zero','')
,('Nagi no Asukara','Nagi-Asu: A Lull in the Sea')
,('Uchiage Hanabi','Fireworks')
,('Samurai Champloo','')
,('OreGairu','My Teen Romantic Comedy SNAFU')
,('Digimon','Irozuku Sekai no Ashita kara')
,('Aria','')
,('Your Name','Kimi no Na wa')
,('Tate no Yuusha no Nariagari','The Rising of the Shield Hero')
,('Guilty Crown','')
,('Fullmetal Alchemist: Brotherhood','')
,('GReeeeN','')
,('Domestic na Kanojo','Domestic Girlfriend')
,('Maquia: When the Promised Flower Blooms','')
,('Pokemon','')
,('Your Lie in April','Shigatsu wa Kimi no Uso')
,('The Quintessential Quintuplets','5-Toubun no Hanayome')
,('A Silent Voice','Koe no Katachi')
,('Attack on Titan','')
,('Original','')
,('Miscellaneous','')
,('Irozuku Sekai no Ashita kara','')
,('Black Clover','')
,('The Legend of Zelda','')
;