INSERT INTO geki_data.matches (title,event_id,match_type_id,match_status_id) VALUES 
('November 2018 Arrangement Competition',1,3,4)
,('December 2018 Christmas Edition',2,3,4)
,('Nagi no Asukara OP1 - lull ~Soshite Bokura wa~',3,4,4)
,('Fireworks - Uchiage Hanabi',3,4,4)
,('Samurai Champloo ED - Shiki no Uta',3,4,4)
,('OreGairu S2 ED - Everyday World',3,4,4)
,('Digimon - Butterfly',3,4,4)
,('Original Composition',3,4,4)
,('Irozuku Sekai no Ashita kara OP - 17-sai',4,4,4)
,('Aria the Natural OP - Euforia',4,4,4)
,('Original Composition',4,4,4)
,('Your Name - Nandemonaiya',4,4,4)
,('Original Composition',4,4,4)
,('The Rising of the Shield Hero ED - Kimi no Namae',4,4,4)
,('Guilty Crown OP - My Dearest',4,4,4)
,('Digimon Adventure 2 - Break Up!',4,4,4)
,('Fullmetal Alchemist: Brotherhood OP3 - Golden Time Lover',4,2,4)
,('GReeeeN - Kiseki',4,4,4)
,('Domestic na Kanojo OP - Kawaki wo Ameku',6,4,4)
,('Gotoubun no Hanayome OP - Gotoubun no Kimochi',6,4,4)
,('Pokemon: The Johto Journeys Theme',6,4,4)
,('Kaguya-sama: Love Is War ED - Sentimental Crisis',6,4,2)
,('A Silent Voice - Lit',6,4,4)
,('Black Clover OP3 - Black Rover',6,4,4)
,('Happy Birthday',6,4,4)
,('Attack on Titan S3 Part 2 OP - Shoukei to Shikabane no Michi',6,4,4)
,('SWEET vs Spicy - Maquia - viator',7,2,4)
,('March/April 2019 Themed Monthly Competition',5,3,2)
;